package cost;

// Generated 2015-8-20 14:27:22 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * Cost generated by hbm2java
 */
public class Cost implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -520629415252361133L;
    private BigDecimal id;
    private BigDecimal year;
    private BigDecimal month;
    private BigDecimal day;
    private BigDecimal cost;

    public Cost() {
    }

    public Cost(BigDecimal id, BigDecimal year, BigDecimal month,
	    BigDecimal day, BigDecimal cost) {
	this.id = id;
	this.year = year;
	this.month = month;
	this.day = day;
	this.cost = cost;
    }

    public BigDecimal getId() {
	return this.id;
    }

    public void setId(BigDecimal id) {
	this.id = id;
    }

    public BigDecimal getYear() {
	return this.year;
    }

    public void setYear(BigDecimal year) {
	this.year = year;
    }

    public BigDecimal getMonth() {
	return this.month;
    }

    public void setMonth(BigDecimal month) {
	this.month = month;
    }

    public BigDecimal getDay() {
	return this.day;
    }

    public void setDay(BigDecimal day) {
	this.day = day;
    }

    public BigDecimal getCost() {
	return this.cost;
    }

    public void setCost(BigDecimal cost) {
	this.cost = cost;
    }

}
