package employee;

// Generated 2015-8-20 14:27:22 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import post.Post;

import department.Department;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 8910864579661824739L;
    private BigDecimal empId;
    private Post post;
    private String phone;
    private String name;
    private boolean gender;
    private Date birthday;
    private String nation;
    private boolean marriage;
    private String address;
    private String habit;
    private String health;
    private String major;
    private String mail;
    private String education;
    private String skill;
    private Date workDate = new Date();
    private BigDecimal wage = new BigDecimal(0);
    private byte state = 0;
    private short evalue = 0;

    public Employee() {
    }

    public Employee(BigDecimal empId, Department department, Post post,
	    String phone, String name, boolean gender, Date birthday,
	    String nation, boolean marriage, String address, String habit,
	    String health, Date workDate, BigDecimal wage, byte state,
	    short evalue) {
	this.empId = empId;
	this.post = post;
	this.phone = phone;
	this.name = name;
	this.gender = gender;
	this.birthday = birthday;
	this.nation = nation;
	this.marriage = marriage;
	this.address = address;
	this.habit = habit;
	this.health = health;
	this.workDate = workDate;
	this.wage = wage;
	this.state = state;
	this.evalue = evalue;
    }

    public Employee(BigDecimal empId, Department department, Post post,
	    String phone, String name, boolean gender, Date birthday,
	    String nation, boolean marriage, String address, String habit,
	    String health, String major, String mail, String education,
	    String skill, Date workDate, BigDecimal wage, byte state,
	    short evalue) {
	this.empId = empId;
	this.post = post;
	this.phone = phone;
	this.name = name;
	this.gender = gender;
	this.birthday = birthday;
	this.nation = nation;
	this.marriage = marriage;
	this.address = address;
	this.habit = habit;
	this.health = health;
	this.major = major;
	this.mail = mail;
	this.education = education;
	this.skill = skill;
	this.workDate = workDate;
	this.wage = wage;
	this.state = state;
	this.evalue = evalue;
    }

    public BigDecimal getEmpId() {
	return this.empId;
    }

    public Employee setEmpId(BigDecimal empId) {
	this.empId = empId;
	return this;
    }

    public Post getPost() {
	return this.post;
    }

    public Employee setPost(Post post) {
	this.post = post;
	return this;
    }

    public String getPhone() {
	return this.phone;
    }

    public Employee setPhone(String phone) {
	this.phone = phone;
	return this;
    }

    public String getName() {
	return this.name;
    }

    public Employee setName(String name) {
	this.name = name;
	return this;
    }

    public boolean isGender() {
	return this.gender;
    }

    public Employee setGender(boolean gender) {
	this.gender = gender;
	return this;
    }

    public Date getBirthday() {
	return this.birthday;
    }

    public Employee setBirthday(Date birthday) {
	this.birthday = birthday;
	return this;
    }

    public String getNation() {
	return this.nation;
    }

    public Employee setNation(String nation) {
	this.nation = nation;
	return this;
    }

    public boolean isMarriage() {
	return this.marriage;
    }

    public Employee setMarriage(boolean marriage) {
	this.marriage = marriage;
	return this;
    }

    public String getAddress() {
	return this.address;
    }

    public Employee setAddress(String address) {
	this.address = address;
	return this;
    }

    public String getHabit() {
	return this.habit;
    }

    public Employee setHabit(String habit) {
	this.habit = habit;
	return this;
    }

    public String getHealth() {
	return this.health;
    }

    public Employee setHealth(String health) {
	this.health = health;
	return this;
    }

    public String getMajor() {
	return this.major;
    }

    public Employee setMajor(String major) {
	this.major = major;
	return this;
    }

    public String getMail() {
	return this.mail;
    }

    public Employee setMail(String mail) {
	this.mail = mail;
	return this;
    }

    public String getEducation() {
	return this.education;
    }

    public Employee setEducation(String education) {
	this.education = education;
	return this;
    }

    public String getSkill() {
	return this.skill;
    }

    public Employee setSkill(String skill) {
	this.skill = skill;
	return this;
    }

    public Date getWorkDate() {
	return this.workDate;
    }

    public Employee setWorkDate(Date workDate) {
	this.workDate = workDate;
	return this;
    }

    public BigDecimal getWage() {
	return this.wage;
    }

    public Employee setWage(BigDecimal wage) {
	this.wage = wage;
	return this;
    }

    public byte getState() {
	return this.state;
    }

    public Employee setState(byte state) {
	this.state = state;
	return this;
    }

    public short getEvalue() {
	return this.evalue;
    }

    public Employee setEvalue(short evalue) {
	this.evalue = evalue;
	return this;
    }

    @Override
    public String toString() {
	return "Employee [empId=" + empId + ", phone=" + phone + ", name="
		+ name + ", gender=" + gender + ", birthday=" + birthday
		+ ", nation=" + nation + ", marriage=" + marriage
		+ ", address=" + address + ", habit=" + habit + ", health="
		+ health + ", major=" + major + ", mail=" + mail
		+ ", education=" + education + ", skill=" + skill
		+ ", workDate=" + workDate + ", wage=" + wage + ", state="
		+ state + ", evalue=" + evalue + "]";
    }

    @Override
    public boolean equals(Object obj) {
	if (this == obj)
	    return true;
	if (!(obj instanceof Employee))
	    return false;

	final Employee employee = (Employee) obj;

	if (!employee.getPhone().equals(phone))
	    return false;

	return true;
    }

    @Override
    public int hashCode() {
	return phone.hashCode();
    }

}
