package post;

// Generated 2015-8-20 14:27:22 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import demand.Demand;
import department.Department;
import employee.Employee;

/**
 * Post generated by hbm2java
 */
public class Post implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 6630175745708800442L;
    private BigDecimal postId;
    private Department department;
    private String name;
    private Set<Demand> demands = new HashSet<Demand>(0);
    private Set<Employee> employees = new HashSet<Employee>(0);

    public Post() {
    }

    public Post(BigDecimal postId, Department department, String name) {
	this.postId = postId;
	this.department = department;
	this.name = name;
    }

    public Post(BigDecimal postId, Department department, String name,
	    Set<Demand> demands, Set<Employee> employees) {
	this.postId = postId;
	this.department = department;
	this.name = name;
	this.demands = demands;
	this.employees = employees;
    }

    public BigDecimal getPostId() {
	return this.postId;
    }

    public Post setPostId(BigDecimal postId) {
	this.postId = postId;
	return this;
    }

    public Department getDepartment() {
	return this.department;
    }

    public Post setDepartment(Department department) {
	this.department = department;
	return this;
    }

    public String getName() {
	return this.name;
    }

    public Post setName(String name) {
	this.name = name;
	return this;
    }

    public Set<Demand> getDemands() {
	return this.demands;
    }

    public Post addDemand(Demand demand) {
	if (demand == null)
	    return this;
	if (!demand.getPost().equals(this)) {
	    demand.getPost().getDemands().remove(demand);
	}
	demand.setPost(this);
	this.demands.add(demand);
	return this;
    }

    public Post setDemands(Set<Demand> demands) {
	this.demands = demands;
	return this;
    }

    public Set<Employee> getEmployees() {
	return this.employees;
    }

    public Post addEmployee(Employee employee) {
	if (employee == null)
	    return this;
	if (!employee.getPost().equals(this)) {
	    employee.getPost().getEmployees().remove(employee);
	}
	employee.setPost(this);
	this.employees.add(employee);
	return this;
    }

    public Post setEmployees(Set<Employee> employees) {
	this.employees = employees;
	return this;
    }

    @Override
    public String toString() {
	return "Post [postId=" + postId + ", name=" + name + ", demands="
		+ demands + ", employees=" + employees + "]";
    }

    @Override
    public boolean equals(Object obj) {
	if (this == obj)
	    return true;
	if (!(obj instanceof Post))
	    return false;

	final Post post = (Post) obj;

	if (!post.getName().equals(name))
	    return false;

	return true;
    }

    @Override
    public int hashCode() {
	return name.hashCode();
    }

}
