package schedule;

// Generated 2015-8-20 14:27:22 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import demand.Demand;

/**
 * Schedule generated by hbm2java
 */
public class Schedule implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 5739733974730773934L;
    private BigDecimal scheId;
    private String name;
    private BigDecimal cost = new BigDecimal(0);
    private boolean state = true;
    private Set<Demand> demands = new HashSet<Demand>(0);

    public Schedule() {
    }

    public Schedule(BigDecimal scheId, String name, BigDecimal cost,
	    boolean state) {
	this.scheId = scheId;
	this.name = name;
	this.cost = cost;
	this.state = state;
    }

    public Schedule(BigDecimal scheId, String name, BigDecimal cost,
	    boolean state, Set<Demand> demands) {
	this.scheId = scheId;
	this.name = name;
	this.cost = cost;
	this.state = state;
	this.demands = demands;
    }

    public BigDecimal getScheId() {
	return this.scheId;
    }

    public Schedule setScheId(BigDecimal scheId) {
	this.scheId = scheId;
	return this;
    }

    public String getName() {
	return this.name;
    }

    public Schedule setName(String name) {
	this.name = name;
	return this;
    }

    public BigDecimal getCost() {
	return this.cost;
    }

    public Schedule setCost(BigDecimal cost) {
	this.cost = cost;
	return this;
    }

    public boolean isState() {
	return this.state;
    }

    public Schedule setState(boolean state) {
	this.state = state;
	return this;
    }

    public Set<Demand> getDemands() {
	return this.demands;
    }

    public Schedule addDemand(Demand demand) {
	if (demand == null)
	    return this;
	if ((demand.getSchedule() != null)
		&& (!demand.getSchedule().equals(this))) {
	    demand.getSchedule().getDemands().remove(demand);
	}
	demand.setSchedule(this);
	this.demands.add(demand);
	return this;
    }

    public Schedule setDemands(Set<Demand> demands) {
	this.demands = demands;
	return this;
    }

    @Override
    public String toString() {
	return "Schedule [scheId=" + scheId + ", name=" + name + ", cost="
		+ cost + ", state=" + state + ", demands=" + demands + "]";
    }

    @Override
    public boolean equals(Object obj) {
	if (this == obj)
	    return true;
	if (!(obj instanceof Schedule))
	    return false;

	final Schedule schedule = (Schedule) obj;

	if (!schedule.getName().equals(name))
	    return false;

	return true;
    }

    @Override
    public int hashCode() {
	return name.hashCode();
    }

}
