package applicant;

// Generated 2015-8-20 14:27:22 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import demand.Demand;

/**
 * Applicant generated by hbm2java
 */
public class Applicant implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -3958518823057461269L;
    private BigDecimal appId;
    private Demand demand;
    private String phone;
    private String name;
    private boolean gender;
    private Date birthday;
    private String nation;
    private boolean marriage;
    private String address;
    private String habit;
    private String health;
    private String major;
    private String mail;
    private String education;
    private String skill;
    private Date viewDate;

    public Applicant() {
    }

    public Applicant(BigDecimal appId, Demand demand, String phone,
	    String name, boolean gender, Date birthday, String nation,
	    boolean marriage, String address, String habit, String health) {
	this.appId = appId;
	this.demand = demand;
	this.phone = phone;
	this.name = name;
	this.gender = gender;
	this.birthday = birthday;
	this.nation = nation;
	this.marriage = marriage;
	this.address = address;
	this.habit = habit;
	this.health = health;
    }

    public Applicant(BigDecimal appId, Demand demand, String phone,
	    String name, boolean gender, Date birthday, String nation,
	    boolean marriage, String address, String habit, String health,
	    String major, String mail, String education, String skill,
	    Date viewDate) {
	this.appId = appId;
	this.demand = demand;
	this.phone = phone;
	this.name = name;
	this.gender = gender;
	this.birthday = birthday;
	this.nation = nation;
	this.marriage = marriage;
	this.address = address;
	this.habit = habit;
	this.health = health;
	this.major = major;
	this.mail = mail;
	this.education = education;
	this.skill = skill;
	this.viewDate = viewDate;
    }

    public BigDecimal getAppId() {
	return this.appId;
    }

    public Applicant setAppId(BigDecimal appId) {
	this.appId = appId;
	return this;
    }

    public Demand getDemand() {
	return this.demand;
    }

    public Applicant setDemand(Demand demand) {
	this.demand = demand;
	return this;
    }

    public String getPhone() {
	return this.phone;
    }

    public Applicant setPhone(String phone) {
	this.phone = phone;
	return this;
    }

    public String getName() {
	return this.name;
    }

    public Applicant setName(String name) {
	this.name = name;
	return this;
    }

    public boolean isGender() {
	return this.gender;
    }

    public Applicant setGender(boolean gender) {
	this.gender = gender;
	return this;
    }

    public Date getBirthday() {
	return this.birthday;
    }

    public Applicant setBirthday(Date birthday) {
	this.birthday = birthday;
	return this;
    }

    public String getNation() {
	return this.nation;
    }

    public Applicant setNation(String nation) {
	this.nation = nation;
	return this;
    }

    public boolean isMarriage() {
	return this.marriage;
    }

    public Applicant setMarriage(boolean marriage) {
	this.marriage = marriage;
	return this;
    }

    public String getAddress() {
	return this.address;
    }

    public Applicant setAddress(String address) {
	this.address = address;
	return this;
    }

    public String getHabit() {
	return this.habit;
    }

    public Applicant setHabit(String habit) {
	this.habit = habit;
	return this;
    }

    public String getHealth() {
	return this.health;
    }

    public Applicant setHealth(String health) {
	this.health = health;
	return this;
    }

    public String getMajor() {
	return this.major;
    }

    public Applicant setMajor(String major) {
	this.major = major;
	return this;
    }

    public String getMail() {
	return this.mail;
    }

    public Applicant setMail(String mail) {
	this.mail = mail;
	return this;
    }

    public String getEducation() {
	return this.education;
    }

    public Applicant setEducation(String education) {
	this.education = education;
	return this;
    }

    public String getSkill() {
	return this.skill;
    }

    public Applicant setSkill(String skill) {
	this.skill = skill;
	return this;
    }

    public Date getViewDate() {
	return this.viewDate;
    }

    public Applicant setViewDate(Date viewDate) {
	this.viewDate = viewDate;
	return this;
    }

    @Override
    public String toString() {
	return "Applicant [appId=" + appId + ", phone=" + phone + ", name="
		+ name + ", gender=" + gender + ", birthday=" + birthday
		+ ", nation=" + nation + ", marriage=" + marriage
		+ ", address=" + address + ", habit=" + habit + ", health="
		+ health + ", major=" + major + ", mail=" + mail
		+ ", education=" + education + ", skill=" + skill
		+ ", viewDate=" + viewDate + "]";
    }

    @Override
    public boolean equals(Object obj) {
	if (this == obj)
	    return true;
	if (!(obj instanceof Applicant))
	    return false;

	final Applicant applicant = (Applicant) obj;

	if (!applicant.getPhone().equals(phone))
	    return false;

	return true;
    }

    @Override
    public int hashCode() {
	return phone.hashCode();
    }

}
